import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/shared/header/Header";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className="dark antialiased"
				style={{
					fontFamily:
						'"Hiragino Kaku Gothic ProN", "ヒラギノ角ゴ ProN W3", "Hiragino Kaku Gothic Pro", "ヒラギノ角ゴ Pro W3", "メイリオ", Meiryo, "游ゴシック", YuGothic, sans-serif',
				}}
			>
				<div className="flex min-h-dvh flex-col gap-16">
					<Header />
					<div className="flex w-full flex-1 justify-center px-6 md:px-4">
						<div className="container w-full">{children}</div>
					</div>
				</div>
				<Toaster richColors position="top-center" />
			</body>
		</html>
	);
}
